//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QService.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class kiosk_transdetail_clinic_choose
    {
        public int transdetail_clinic_choose_seq { get; set; }
        public int slip_seq { get; set; }
        public int clinic_seq { get; set; }
        public string clinic_code { get; set; }
        public string clinic_name { get; set; }
        public string clinic_location { get; set; }
        public string clinic_desc { get; set; }
        public string clinic_type { get; set; }
        public string flag_clinic_open { get; set; }
        public string flag_clinic_quota_full { get; set; }
        public string flag_is_quota_full { get; set; }
        public System.DateTime crtd_dttm { get; set; }
        public string crtd_by { get; set; }
        public Nullable<System.DateTime> last_chg_dttm { get; set; }
        public string last_chg_by { get; set; }
    }
}
