//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QService.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class kiosk_transdetail_right
    {
        public int transdetail_right_seq { get; set; }
        public int slip_seq { get; set; }
        public string right_group_code { get; set; }
        public string right_group_name { get; set; }
        public string right_code { get; set; }
        public string right_name { get; set; }
        public string contact_type { get; set; }
        public string right_cont_code { get; set; }
        public string right_cont_name { get; set; }
        public Nullable<System.DateTime> right_start_date { get; set; }
        public Nullable<System.DateTime> right_e_date { get; set; }
        public Nullable<System.DateTime> right_last_date { get; set; }
        public System.DateTime crtd_dttm { get; set; }
        public string crtd_by { get; set; }
        public Nullable<System.DateTime> last_chg_dttm { get; set; }
        public string last_chg_by { get; set; }
        public string right_type_code { get; set; }
    }
}
