//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QService.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class kiosk_transdetail_MissAppoint
    {
        public int transdetail_missappoint_seq { get; set; }
        public int slip_seq { get; set; }
        public Nullable<System.DateTime> missappoint_date { get; set; }
        public Nullable<System.TimeSpan> missappoint_time_start { get; set; }
        public Nullable<System.TimeSpan> missappoint_time_end { get; set; }
        public string missappoint_clinic_code { get; set; }
        public string missappoint_clinic_name { get; set; }
        public string missappoint_clinic_location { get; set; }
        public string missappoint_doctor_code { get; set; }
        public string missappoint_doctor_name { get; set; }
        public Nullable<System.DateTime> make_appoint_date { get; set; }
        public Nullable<System.TimeSpan> make_appoint_time { get; set; }
        public string missappoint_status_code { get; set; }
        public string missappoint_status_name { get; set; }
        public string missappoint_right_group_code { get; set; }
        public string missappoint_right_group_name { get; set; }
        public string missappoint_right_code { get; set; }
        public string missappoint_right_name { get; set; }
        public string missappoint_contact_type { get; set; }
        public string missappoint_right_cont_code { get; set; }
        public string missappoint_right_cont_name { get; set; }
        public Nullable<System.DateTime> missappoint_right_start_date { get; set; }
        public Nullable<System.DateTime> missappoint_right_e_date { get; set; }
        public string missappoint_right_ref_no { get; set; }
        public string flag_first_clinic_contact { get; set; }
        public string flag_expire { get; set; }
        public string flag_pay { get; set; }
        public System.DateTime crtd_dttm { get; set; }
        public string crtd_by { get; set; }
        public Nullable<System.DateTime> last_chg_dttm { get; set; }
        public string last_chg_by { get; set; }
    }
}
