//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QService.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class Kiosk_Chula_iPadEntities : DbContext
    {
        public Kiosk_Chula_iPadEntities()
            : base("name=Kiosk_Chula_iPadEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<kiosk_building> kiosk_building { get; set; }
        public virtual DbSet<kiosk_com> kiosk_com { get; set; }
        public virtual DbSet<kiosk_computer> kiosk_computer { get; set; }
        public virtual DbSet<kiosk_control> kiosk_control { get; set; }
        public virtual DbSet<kiosk_locat> kiosk_locat { get; set; }
        public virtual DbSet<kiosk_map_qexpress> kiosk_map_qexpress { get; set; }
        public virtual DbSet<kiosk_q_log> kiosk_q_log { get; set; }
        public virtual DbSet<kiosk_transdetail_appoint> kiosk_transdetail_appoint { get; set; }
        public virtual DbSet<kiosk_transdetail_clinic_choose> kiosk_transdetail_clinic_choose { get; set; }
        public virtual DbSet<kiosk_transhead> kiosk_transhead { get; set; }
        public virtual DbSet<kiosk_user> kiosk_user { get; set; }
        public virtual DbSet<kiosk_user_group> kiosk_user_group { get; set; }
        public virtual DbSet<kiosk_transdetail_MissAppoint> kiosk_transdetail_MissAppoint { get; set; }
    
        public virtual int q_expr_ins_kiosk_map_qexpress_ipad(Nullable<int> slipSeq_Express, string queue_no_Express, Nullable<int> slipSeq_Q, string queue_no_q, string active_flag, string crtd_by)
        {
            var slipSeq_ExpressParameter = slipSeq_Express.HasValue ?
                new ObjectParameter("slipSeq_Express", slipSeq_Express) :
                new ObjectParameter("slipSeq_Express", typeof(int));
    
            var queue_no_ExpressParameter = queue_no_Express != null ?
                new ObjectParameter("queue_no_Express", queue_no_Express) :
                new ObjectParameter("queue_no_Express", typeof(string));
    
            var slipSeq_QParameter = slipSeq_Q.HasValue ?
                new ObjectParameter("slipSeq_Q", slipSeq_Q) :
                new ObjectParameter("slipSeq_Q", typeof(int));
    
            var queue_no_qParameter = queue_no_q != null ?
                new ObjectParameter("queue_no_q", queue_no_q) :
                new ObjectParameter("queue_no_q", typeof(string));
    
            var active_flagParameter = active_flag != null ?
                new ObjectParameter("active_flag", active_flag) :
                new ObjectParameter("active_flag", typeof(string));
    
            var crtd_byParameter = crtd_by != null ?
                new ObjectParameter("crtd_by", crtd_by) :
                new ObjectParameter("crtd_by", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("q_expr_ins_kiosk_map_qexpress_ipad", slipSeq_ExpressParameter, queue_no_ExpressParameter, slipSeq_QParameter, queue_no_qParameter, active_flagParameter, crtd_byParameter);
        }
    
        public virtual int q_expr_ins_kiosk_qExpress_log_ipad(string queue_no, string flag_queue, string q_action, string crtd_by)
        {
            var queue_noParameter = queue_no != null ?
                new ObjectParameter("queue_no", queue_no) :
                new ObjectParameter("queue_no", typeof(string));
    
            var flag_queueParameter = flag_queue != null ?
                new ObjectParameter("flag_queue", flag_queue) :
                new ObjectParameter("flag_queue", typeof(string));
    
            var q_actionParameter = q_action != null ?
                new ObjectParameter("q_action", q_action) :
                new ObjectParameter("q_action", typeof(string));
    
            var crtd_byParameter = crtd_by != null ?
                new ObjectParameter("crtd_by", crtd_by) :
                new ObjectParameter("crtd_by", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("q_expr_ins_kiosk_qExpress_log_ipad", queue_noParameter, flag_queueParameter, q_actionParameter, crtd_byParameter);
        }
    
        public virtual int q_expr_ins_kiosk_transdetail_right(Nullable<int> slip_seq, string right_group_code, string right_group_name, string right_code, string right_name, string contact_type, string right_cont_code, string right_cont_name, Nullable<System.DateTime> right_start_date, Nullable<System.DateTime> right_e_date, Nullable<System.DateTime> right_last_date, string crtd_by)
        {
            var slip_seqParameter = slip_seq.HasValue ?
                new ObjectParameter("slip_seq", slip_seq) :
                new ObjectParameter("slip_seq", typeof(int));
    
            var right_group_codeParameter = right_group_code != null ?
                new ObjectParameter("right_group_code", right_group_code) :
                new ObjectParameter("right_group_code", typeof(string));
    
            var right_group_nameParameter = right_group_name != null ?
                new ObjectParameter("right_group_name", right_group_name) :
                new ObjectParameter("right_group_name", typeof(string));
    
            var right_codeParameter = right_code != null ?
                new ObjectParameter("right_code", right_code) :
                new ObjectParameter("right_code", typeof(string));
    
            var right_nameParameter = right_name != null ?
                new ObjectParameter("right_name", right_name) :
                new ObjectParameter("right_name", typeof(string));
    
            var contact_typeParameter = contact_type != null ?
                new ObjectParameter("contact_type", contact_type) :
                new ObjectParameter("contact_type", typeof(string));
    
            var right_cont_codeParameter = right_cont_code != null ?
                new ObjectParameter("right_cont_code", right_cont_code) :
                new ObjectParameter("right_cont_code", typeof(string));
    
            var right_cont_nameParameter = right_cont_name != null ?
                new ObjectParameter("right_cont_name", right_cont_name) :
                new ObjectParameter("right_cont_name", typeof(string));
    
            var right_start_dateParameter = right_start_date.HasValue ?
                new ObjectParameter("right_start_date", right_start_date) :
                new ObjectParameter("right_start_date", typeof(System.DateTime));
    
            var right_e_dateParameter = right_e_date.HasValue ?
                new ObjectParameter("right_e_date", right_e_date) :
                new ObjectParameter("right_e_date", typeof(System.DateTime));
    
            var right_last_dateParameter = right_last_date.HasValue ?
                new ObjectParameter("right_last_date", right_last_date) :
                new ObjectParameter("right_last_date", typeof(System.DateTime));
    
            var crtd_byParameter = crtd_by != null ?
                new ObjectParameter("crtd_by", crtd_by) :
                new ObjectParameter("crtd_by", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("q_expr_ins_kiosk_transdetail_right", slip_seqParameter, right_group_codeParameter, right_group_nameParameter, right_codeParameter, right_nameParameter, contact_typeParameter, right_cont_codeParameter, right_cont_nameParameter, right_start_dateParameter, right_e_dateParameter, right_last_dateParameter, crtd_byParameter);
        }
    
        public virtual ObjectResult<Nullable<decimal>> q_expr_ins_kiosk_transhead_ipad(string slip_type, string slip_type_detail, string slip_type_flag, Nullable<System.DateTime> register_date, Nullable<System.TimeSpan> register_time, Nullable<System.TimeSpan> out_time, string building_code, string floor, string zone, string locat_code, string locat_name, string com_code, Nullable<int> computer_code, string computer_name, string kiosk_group_code, string time_type, string idcard_no, string hn_no, string pateint_name, Nullable<System.DateTime> pateint_dob, string patient_file_location_type, string patient_file_location_code, string patient_file_location_name, Nullable<System.DateTime> patient_file_asof, string queue_no, string flag_queue, string queue_status, string pateint_flag, string flag_change_right, string flag_choose_right, string flag_remark_right, string print_result, string crtd_by)
        {
            var slip_typeParameter = slip_type != null ?
                new ObjectParameter("slip_type", slip_type) :
                new ObjectParameter("slip_type", typeof(string));
    
            var slip_type_detailParameter = slip_type_detail != null ?
                new ObjectParameter("slip_type_detail", slip_type_detail) :
                new ObjectParameter("slip_type_detail", typeof(string));
    
            var slip_type_flagParameter = slip_type_flag != null ?
                new ObjectParameter("slip_type_flag", slip_type_flag) :
                new ObjectParameter("slip_type_flag", typeof(string));
    
            var register_dateParameter = register_date.HasValue ?
                new ObjectParameter("register_date", register_date) :
                new ObjectParameter("register_date", typeof(System.DateTime));
    
            var register_timeParameter = register_time.HasValue ?
                new ObjectParameter("register_time", register_time) :
                new ObjectParameter("register_time", typeof(System.TimeSpan));
    
            var out_timeParameter = out_time.HasValue ?
                new ObjectParameter("out_time", out_time) :
                new ObjectParameter("out_time", typeof(System.TimeSpan));
    
            var building_codeParameter = building_code != null ?
                new ObjectParameter("building_code", building_code) :
                new ObjectParameter("building_code", typeof(string));
    
            var floorParameter = floor != null ?
                new ObjectParameter("floor", floor) :
                new ObjectParameter("floor", typeof(string));
    
            var zoneParameter = zone != null ?
                new ObjectParameter("zone", zone) :
                new ObjectParameter("zone", typeof(string));
    
            var locat_codeParameter = locat_code != null ?
                new ObjectParameter("locat_code", locat_code) :
                new ObjectParameter("locat_code", typeof(string));
    
            var locat_nameParameter = locat_name != null ?
                new ObjectParameter("locat_name", locat_name) :
                new ObjectParameter("locat_name", typeof(string));
    
            var com_codeParameter = com_code != null ?
                new ObjectParameter("com_code", com_code) :
                new ObjectParameter("com_code", typeof(string));
    
            var computer_codeParameter = computer_code.HasValue ?
                new ObjectParameter("computer_code", computer_code) :
                new ObjectParameter("computer_code", typeof(int));
    
            var computer_nameParameter = computer_name != null ?
                new ObjectParameter("computer_name", computer_name) :
                new ObjectParameter("computer_name", typeof(string));
    
            var kiosk_group_codeParameter = kiosk_group_code != null ?
                new ObjectParameter("kiosk_group_code", kiosk_group_code) :
                new ObjectParameter("kiosk_group_code", typeof(string));
    
            var time_typeParameter = time_type != null ?
                new ObjectParameter("time_type", time_type) :
                new ObjectParameter("time_type", typeof(string));
    
            var idcard_noParameter = idcard_no != null ?
                new ObjectParameter("idcard_no", idcard_no) :
                new ObjectParameter("idcard_no", typeof(string));
    
            var hn_noParameter = hn_no != null ?
                new ObjectParameter("hn_no", hn_no) :
                new ObjectParameter("hn_no", typeof(string));
    
            var pateint_nameParameter = pateint_name != null ?
                new ObjectParameter("pateint_name", pateint_name) :
                new ObjectParameter("pateint_name", typeof(string));
    
            var pateint_dobParameter = pateint_dob.HasValue ?
                new ObjectParameter("pateint_dob", pateint_dob) :
                new ObjectParameter("pateint_dob", typeof(System.DateTime));
    
            var patient_file_location_typeParameter = patient_file_location_type != null ?
                new ObjectParameter("patient_file_location_type", patient_file_location_type) :
                new ObjectParameter("patient_file_location_type", typeof(string));
    
            var patient_file_location_codeParameter = patient_file_location_code != null ?
                new ObjectParameter("patient_file_location_code", patient_file_location_code) :
                new ObjectParameter("patient_file_location_code", typeof(string));
    
            var patient_file_location_nameParameter = patient_file_location_name != null ?
                new ObjectParameter("patient_file_location_name", patient_file_location_name) :
                new ObjectParameter("patient_file_location_name", typeof(string));
    
            var patient_file_asofParameter = patient_file_asof.HasValue ?
                new ObjectParameter("patient_file_asof", patient_file_asof) :
                new ObjectParameter("patient_file_asof", typeof(System.DateTime));
    
            var queue_noParameter = queue_no != null ?
                new ObjectParameter("queue_no", queue_no) :
                new ObjectParameter("queue_no", typeof(string));
    
            var flag_queueParameter = flag_queue != null ?
                new ObjectParameter("flag_queue", flag_queue) :
                new ObjectParameter("flag_queue", typeof(string));
    
            var queue_statusParameter = queue_status != null ?
                new ObjectParameter("queue_status", queue_status) :
                new ObjectParameter("queue_status", typeof(string));
    
            var pateint_flagParameter = pateint_flag != null ?
                new ObjectParameter("pateint_flag", pateint_flag) :
                new ObjectParameter("pateint_flag", typeof(string));
    
            var flag_change_rightParameter = flag_change_right != null ?
                new ObjectParameter("flag_change_right", flag_change_right) :
                new ObjectParameter("flag_change_right", typeof(string));
    
            var flag_choose_rightParameter = flag_choose_right != null ?
                new ObjectParameter("flag_choose_right", flag_choose_right) :
                new ObjectParameter("flag_choose_right", typeof(string));
    
            var flag_remark_rightParameter = flag_remark_right != null ?
                new ObjectParameter("flag_remark_right", flag_remark_right) :
                new ObjectParameter("flag_remark_right", typeof(string));
    
            var print_resultParameter = print_result != null ?
                new ObjectParameter("print_result", print_result) :
                new ObjectParameter("print_result", typeof(string));
    
            var crtd_byParameter = crtd_by != null ?
                new ObjectParameter("crtd_by", crtd_by) :
                new ObjectParameter("crtd_by", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<decimal>>("q_expr_ins_kiosk_transhead_ipad", slip_typeParameter, slip_type_detailParameter, slip_type_flagParameter, register_dateParameter, register_timeParameter, out_timeParameter, building_codeParameter, floorParameter, zoneParameter, locat_codeParameter, locat_nameParameter, com_codeParameter, computer_codeParameter, computer_nameParameter, kiosk_group_codeParameter, time_typeParameter, idcard_noParameter, hn_noParameter, pateint_nameParameter, pateint_dobParameter, patient_file_location_typeParameter, patient_file_location_codeParameter, patient_file_location_nameParameter, patient_file_asofParameter, queue_noParameter, flag_queueParameter, queue_statusParameter, pateint_flagParameter, flag_change_rightParameter, flag_choose_rightParameter, flag_remark_rightParameter, print_resultParameter, crtd_byParameter);
        }
    
        public virtual ObjectResult<q_expr_search_kiosk_trans_ipad_Result> q_expr_search_kiosk_trans_ipad(string hn_no, string queue_no, string cur_date, Nullable<int> missappoint_month_not_exceed)
        {
            var hn_noParameter = hn_no != null ?
                new ObjectParameter("hn_no", hn_no) :
                new ObjectParameter("hn_no", typeof(string));
    
            var queue_noParameter = queue_no != null ?
                new ObjectParameter("queue_no", queue_no) :
                new ObjectParameter("queue_no", typeof(string));
    
            var cur_dateParameter = cur_date != null ?
                new ObjectParameter("cur_date", cur_date) :
                new ObjectParameter("cur_date", typeof(string));
    
            var missappoint_month_not_exceedParameter = missappoint_month_not_exceed.HasValue ?
                new ObjectParameter("missappoint_month_not_exceed", missappoint_month_not_exceed) :
                new ObjectParameter("missappoint_month_not_exceed", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<q_expr_search_kiosk_trans_ipad_Result>("q_expr_search_kiosk_trans_ipad", hn_noParameter, queue_noParameter, cur_dateParameter, missappoint_month_not_exceedParameter);
        }
    
        public virtual ObjectResult<q_expr_sel_kiosk_com_cat_ipad_Result> q_expr_sel_kiosk_com_cat_ipad(string computer_name)
        {
            var computer_nameParameter = computer_name != null ?
                new ObjectParameter("computer_name", computer_name) :
                new ObjectParameter("computer_name", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<q_expr_sel_kiosk_com_cat_ipad_Result>("q_expr_sel_kiosk_com_cat_ipad", computer_nameParameter);
        }
    
        public virtual ObjectResult<q_expr_sel_kiosk_trans_all_ipad_Result> q_expr_sel_kiosk_trans_all_ipad(string hn_no, string queue_no, string cur_date, Nullable<int> missappoint_month_not_exceed)
        {
            var hn_noParameter = hn_no != null ?
                new ObjectParameter("hn_no", hn_no) :
                new ObjectParameter("hn_no", typeof(string));
    
            var queue_noParameter = queue_no != null ?
                new ObjectParameter("queue_no", queue_no) :
                new ObjectParameter("queue_no", typeof(string));
    
            var cur_dateParameter = cur_date != null ?
                new ObjectParameter("cur_date", cur_date) :
                new ObjectParameter("cur_date", typeof(string));
    
            var missappoint_month_not_exceedParameter = missappoint_month_not_exceed.HasValue ?
                new ObjectParameter("missappoint_month_not_exceed", missappoint_month_not_exceed) :
                new ObjectParameter("missappoint_month_not_exceed", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<q_expr_sel_kiosk_trans_all_ipad_Result>("q_expr_sel_kiosk_trans_all_ipad", hn_noParameter, queue_noParameter, cur_dateParameter, missappoint_month_not_exceedParameter);
        }
    
        public virtual ObjectResult<string> q_expr_sel_login_ipad(string username, string password)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("username", username) :
                new ObjectParameter("username", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("password", password) :
                new ObjectParameter("password", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("q_expr_sel_login_ipad", usernameParameter, passwordParameter);
        }
    
        public virtual int q_expr_upd_kiosk_transhead_queue_status_ipad(Nullable<int> slip_seq, string queue_status, string last_chg_by)
        {
            var slip_seqParameter = slip_seq.HasValue ?
                new ObjectParameter("slip_seq", slip_seq) :
                new ObjectParameter("slip_seq", typeof(int));
    
            var queue_statusParameter = queue_status != null ?
                new ObjectParameter("queue_status", queue_status) :
                new ObjectParameter("queue_status", typeof(string));
    
            var last_chg_byParameter = last_chg_by != null ?
                new ObjectParameter("last_chg_by", last_chg_by) :
                new ObjectParameter("last_chg_by", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("q_expr_upd_kiosk_transhead_queue_status_ipad", slip_seqParameter, queue_statusParameter, last_chg_byParameter);
        }
    }
}
