//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QService.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class kiosk_transhead
    {
        public int slip_seq { get; set; }
        public string slip_no { get; set; }
        public string slip_type { get; set; }
        public string slip_type_detail { get; set; }
        public string slip_type_flag { get; set; }
        public System.DateTime slip_dtm { get; set; }
        public Nullable<System.DateTime> register_date { get; set; }
        public Nullable<System.TimeSpan> register_time { get; set; }
        public Nullable<System.TimeSpan> out_time { get; set; }
        public Nullable<int> client_log_seq { get; set; }
        public string building_code { get; set; }
        public string floor { get; set; }
        public string zone { get; set; }
        public string locat_code { get; set; }
        public string locat_name { get; set; }
        public string com_code { get; set; }
        public int computer_code { get; set; }
        public string kiosk_group_code { get; set; }
        public string time_type { get; set; }
        public string idcard_no { get; set; }
        public string hn_no { get; set; }
        public string pateint_name { get; set; }
        public Nullable<System.DateTime> pateint_dob { get; set; }
        public string patient_file_location_type { get; set; }
        public string patient_file_location_status { get; set; }
        public string patient_file_location_code { get; set; }
        public string patient_file_location_name { get; set; }
        public Nullable<System.DateTime> patient_file_asof { get; set; }
        public string queue_no { get; set; }
        public string flag_queue { get; set; }
        public string queue_status { get; set; }
        public Nullable<int> waiting_qno { get; set; }
        public Nullable<System.TimeSpan> time_gen_waiting_qno { get; set; }
        public string pateint_flag { get; set; }
        public string pateint_service_flag { get; set; }
        public string flag_change_right { get; set; }
        public string flag_choose_right { get; set; }
        public string flag_lab_xray { get; set; }
        public string flag_remark_right { get; set; }
        public string flag_remark_right_group2 { get; set; }
        public string flag_general_pateint { get; set; }
        public string flag_nosend_approve { get; set; }
        public string flag_have_right_approved { get; set; }
        public string flag_dct_ins_treatment_order { get; set; }
        public Nullable<int> q_channel_group_id { get; set; }
        public Nullable<int> q_period_no { get; set; }
        public string flag_print_q_report { get; set; }
        public Nullable<System.DateTime> print_q_report_last_dttm { get; set; }
        public string print_result { get; set; }
        public System.DateTime crtd_dttm { get; set; }
        public string crtd_by { get; set; }
        public Nullable<System.DateTime> last_chg_dttm { get; set; }
        public string last_chg_by { get; set; }
    }
}
