//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QService.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class kiosk_map_qexpress
    {
        public int map_qexpress_seq { get; set; }
        public string slip_no_qexpress { get; set; }
        public string queue_no_qexpress { get; set; }
        public string slip_no_q { get; set; }
        public string queue_no_q { get; set; }
        public Nullable<System.DateTime> trans_dtm { get; set; }
        public string active_flag { get; set; }
        public System.DateTime crtd_dttm { get; set; }
        public string crtd_by { get; set; }
        public Nullable<System.DateTime> last_chg_dttm { get; set; }
        public string last_chg_by { get; set; }
    }
}
