//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QService.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class kiosk_q_log
    {
        public int q_log_seq { get; set; }
        public System.DateTime q_trans_dtm { get; set; }
        public string queue_no { get; set; }
        public string flag_queue { get; set; }
        public string q_action { get; set; }
        public string action_by { get; set; }
        public Nullable<int> channel_no { get; set; }
        public Nullable<int> slip_seq { get; set; }
        public string com_code { get; set; }
        public System.DateTime crtd_dttm { get; set; }
        public string crtd_by { get; set; }
        public Nullable<System.DateTime> last_chg_dttm { get; set; }
        public string last_chg_by { get; set; }
    }
}
