//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QService.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class kiosk_user_group
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public kiosk_user_group()
        {
            this.kiosk_user = new HashSet<kiosk_user>();
        }
    
        public int user_group_code { get; set; }
        public string user_group_name { get; set; }
        public string user_group_desc { get; set; }
        public string building_code { get; set; }
        public string location_floor { get; set; }
        public string active_flag { get; set; }
        public System.DateTime crtd_dttm { get; set; }
        public string crtd_by { get; set; }
        public Nullable<System.DateTime> last_chg_dttm { get; set; }
        public string last_chg_by { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<kiosk_user> kiosk_user { get; set; }
    }
}
