//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QService.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class kiosk_locat
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public kiosk_locat()
        {
            this.kiosk_com = new HashSet<kiosk_com>();
        }
    
        public string locat_code { get; set; }
        public int locat_type_code { get; set; }
        public string locat_name { get; set; }
        public string locat_name_en { get; set; }
        public string building_code { get; set; }
        public string floor { get; set; }
        public string zone { get; set; }
        public string kiosk_group_code { get; set; }
        public string active_flag { get; set; }
        public System.DateTime crtd_dttm { get; set; }
        public string crtd_by { get; set; }
        public Nullable<System.DateTime> last_chg_dttm { get; set; }
        public string last_chg_by { get; set; }
    
        public virtual kiosk_building kiosk_building { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<kiosk_com> kiosk_com { get; set; }
    }
}
